export const UploadItem = [
    {
        FileTitle: "",
        uploadFileBodyText: "",
        uploadFileBtnText: "",
        CoverTitle: "",
        coverBodyText: "",
        coverBtnText: "",
    },
];

export const FormDetails = [
    {
        StepTitle: "",
        FormTitle: "",
        NFTName: "",
        NFTPlaceholderName: "",
        CategoryTitle: "",
        CategoryDropDownTitle: "",
        DescriptionTitleText: "",
        DescriptionPlaceholderText: "",
        RoyalityTitle: "",
        RoyalityDescriptionText: "",
        RoyalityPlaceholderText: "",
        Tab1Title: "",
        Tab2Title: "",
        Tab3Title: "",
        Tab1FieldTitle: "",
        Tab2FieldTitle: "",
        Tab3FieldTitle: "",
        Tab1Placeholder1: "",
        Tab1Placeholder2: "",
        Tab3Placeholder1: "",
        Tab3Placeholder2: "",
        Tab1Description1: "",
        Tab1Description2: "",
        Tab2Description1: "",
        Tab2Description2: "",
        ItemName1: "",
        ItemName2: "",
        MintingTitleText: "",
        MintingDescription: "",
        CreateButtonText: "",
    },
];